# Generated by Django 5.1.1 on 2024-10-02 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
