# Generated by Django 5.1.1 on 2024-10-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0008_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
